Update issue #3
filetrust/k8-performance-use-cases pull request #6
Opened 2020-09-03 04:14 UTC by hongson1981

2020-09-03 13:18 UTC, faisaladnanpeltops commented
@hongson1981 , please create:
1. A diagram and a description how the Artillery pod, Squid pod and a target website are interacting.
2. A pod manifest file to deploy the squid in minikube/k8s cluster
3. A short description how to install the squid pod and test it

2020-09-03 13:20 UTC, faisaladnanpeltops requested changes

2020-09-03 13:20 UTC, faisaladnanpeltops commented on upword-devs/son-ha/entrypoint.sh
> +echo "adaptation_access svc_echo_resp_chain allow all">> $SQUID_DIR/etc/squid.conf
Create a squid.conf file and copy it to the docker image.

2020-09-09 09:08 UTC, DinisCruz approved these changes

2020-09-09 09:08 UTC, merged